# Generated by Django 2.0.9 on 2019-06-18 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='receipt_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rr_receipt_id', models.CharField(default='', max_length=50)),
                ('rr_agreement_number', models.CharField(default='', max_length=50)),
                ('rr_receipt_source', models.CharField(default='', max_length=50)),
                ('rr_receipt_source_id', models.CharField(default='', max_length=50)),
                ('rr_receipt_type', models.CharField(default='', max_length=50)),
                ('rr_receipt_salestax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('rr_receipt_value_net', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('rr_receipt_value_gross', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('rr_receipt_created_on', models.DateTimeField(null=True)),
                ('rr_receipt_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Payment Receipt Record',
                'verbose_name': 'Payment Receipt Record',
                'ordering': ('rr_receipt_id',),
            },
        ),
    ]
