# Generated by Django 2.0.9 on 2019-06-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='receipt_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rt_type_code', models.CharField(max_length=5, unique=True)),
                ('rt_type_description', models.CharField(default='', max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Payment Receipt Types',
                'verbose_name': 'Payment Receipt Type',
                'ordering': ('rt_type_description',),
            },
        ),
    ]
