# Generated by Django 2.0.9 on 2019-06-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_payments', '0002_receipt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt_type',
            name='rt_type_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
