# Generated by Django 2.0.9 on 2019-06-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_payments', '0004_auto_20190618_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt_type',
            name='rt_type_crdr_flag',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='receipt_type',
            name='rt_type_crdr_multiplier',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt_type',
            name='rt_type_description',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
