# Generated by Django 2.0.9 on 2019-01-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchorimport', '0003_auto_20190126_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchorimporttransactiontable',
            name='transnotpostedtoacclink',
            field=models.BooleanField(db_column='TransNotPostedToAccLink'),
        ),
    ]
