# Generated by Django 2.0.9 on 2019-01-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchorimport', '0004_auto_20190126_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchorimporttransactiontable',
            name='transnotpostedtoacclink',
            field=models.NullBooleanField(db_column='TransNotPostedToAccLink'),
        ),
    ]
