# Generated by Django 2.0.9 on 2019-01-26 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anchorimport', '0005_auto_20190126_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anchorimporttransactiontable',
            name='transnotpostedtoacclink',
        ),
    ]
