# Generated by Django 2.0.9 on 2019-01-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchorimport', '0006_remove_anchorimporttransactiontable_transnotpostedtoacclink'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchorimporttransactiontable',
            name='transnotpostedtoacclink',
            field=models.NullBooleanField(db_column='TransNotPostedToAccLink'),
        ),
    ]
