# Generated by Django 2.0.9 on 2019-01-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anchorimport', '0007_anchorimporttransactiontable_transnotpostedtoacclink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnchorimportAgreementClosedAudit',
        ),
    ]
