# Generated by Django 2.0.9 on 2019-01-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchorimport', '0008_delete_anchorimportagreementclosedaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnchorimportAgreementClosedAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreementnumber', models.CharField(db_column='AgreementNumber', max_length=10)),
                ('closeddate', models.DateTimeField(blank=True, db_column='ClosedDate', null=True)),
            ],
            options={
                'ordering': ('agreementnumber', 'closeddate'),
                'verbose_name': 'Agreement Closed Audit',
                'verbose_name_plural': 'Agreement Closed Audit',
                'db_table': 'anchorimport_agreementclosed_audit',
            },
        ),
    ]
