# Generated by Django 2.0.9 on 2019-05-01 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_client_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchHeaders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, db_column='reference', max_length=50, null=True, unique=True)),
                ('total_count', models.IntegerField(blank=True, db_column='total_count', null=True)),
                ('total_amount', models.DecimalField(blank=True, db_column='total_amount', decimal_places=2, max_digits=10, null=True)),
                ('due_date', models.DateField(blank=True, db_column='due_date', null=True)),
                ('info', models.CharField(blank=True, db_column='info', max_length=100, null=True)),
                ('sent', models.DateTimeField(blank=True, db_column='sent_date', null=True)),
                ('response', models.DateTimeField(blank=True, db_column='response_date', null=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_dd_drawdowns_batch_headers',
            },
        ),
        migrations.CreateModel(
            name='DrawDown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_id', models.CharField(db_column='agreement_id', max_length=10)),
                ('reference', models.CharField(blank=True, db_column='reference', max_length=20, null=True)),
                ('dd_reference', models.CharField(blank=True, db_column='dd_reference', max_length=50, null=True)),
                ('customer_name', models.CharField(blank=True, db_column='customer_name', max_length=60, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('due_date', models.DateField(blank=True, db_column='due_date', null=True)),
                ('sort_code', models.CharField(blank=True, db_column='sort_code', max_length=6, null=True)),
                ('account_name', models.CharField(blank=True, db_column='account_name', max_length=60, null=True)),
                ('account_number', models.CharField(blank=True, db_column='account_number', max_length=8, null=True)),
                ('agreement_type', models.CharField(blank=True, db_column='agreement_type', max_length=50, null=True)),
                ('agreement_phase', models.CharField(blank=True, db_column='agreement_phase', max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('batch_header', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_dd_drawdowns.BatchHeaders', to_field='reference')),
                ('ddi_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ncf_dd_status_text', to_field='dd_text_code')),
            ],
            options={
                'db_table': 'core_dd_drawdowns',
            },
        ),
        migrations.CreateModel(
            name='StatusDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_code', models.CharField(choices=[('OPEN', 'OPEN'), ('PROCESSING', 'PROCESSING'), ('SENT', 'SENT'), ('RECEIVED', 'RECEIVED')], db_column='text_code', max_length=20, unique=True)),
                ('text_description', models.CharField(db_column='text_description', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_dd_drawdowns_status_definitions',
            },
        ),
        migrations.AddField(
            model_name='drawdown',
            name='status',
            field=models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core_dd_drawdowns.StatusDefinition', to_field='text_code'),
        ),
        migrations.AddField(
            model_name='drawdown',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchheaders',
            name='status',
            field=models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core_dd_drawdowns.StatusDefinition', to_field='text_code'),
        ),
        migrations.AddField(
            model_name='batchheaders',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
