# Generated by Django 2.0.9 on 2019-05-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_dd_drawdowns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusdefinition',
            name='text_code',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('PROCESSING', 'PROCESSING'), ('SENT', 'SENT'), ('RECEIVED', 'RECEIVED'), ('REMOVED', 'REMOVED')], db_column='text_code', max_length=20, unique=True),
        ),
    ]
