# Generated by Django 2.0.9 on 2019-06-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_dd_drawdowns', '0002_auto_20190521_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResyncDrawdows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extract_type', models.CharField(blank=True, max_length=2, null=True)),
                ('extract_count', models.IntegerField(blank=True, null=True)),
                ('batch_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status_id', models.CharField(blank=True, max_length=20, null=True)),
                ('agreement_id', models.CharField(blank=True, max_length=10, null=True)),
                ('transaction_batch', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'managed': False,
                'db_table': '_GO_Drawdown_Merge',
            },
        ),
    ]
