# Generated by Django 2.0.9 on 2019-06-20 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_dd_drawdowns', '0005_syncdrawdowns'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('released', models.DateTimeField(null=True)),
                ('batch_header', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core_dd_drawdowns.BatchHeaders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
