# Generated by Django 2.0.9 on 2019-06-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_dd_drawdowns', '0006_batchlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchlock',
            name='session_id',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
