# Generated by Django 2.0.9 on 2019-07-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_dd_drawdowns', '0008_batchheaders_sagewisdom_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchheaders',
            name='call_date',
            field=models.DateField(blank=True, db_column='call_date', null=True),
        ),
    ]
