# Generated by Django 2.0.9 on 2019-07-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_dd_drawdowns', '0009_batchheaders_call_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawdown',
            name='agreement_origin_flag',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
