# Generated by Django 2.0.9 on 2019-07-31 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_dd_drawdowns', '0010_drawdown_agreement_origin_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField(null=True)),
                ('response', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('batch_header', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core_dd_drawdowns.BatchHeaders')),
            ],
        ),
    ]
