# Generated by Django 2.0.9 on 2019-08-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_dd_drawdowns', '0014_auto_20190807_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchheaders',
            name='total_amount',
            field=models.DecimalField(blank=True, db_column='total_amount', decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='drawdown',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
