# Generated by Django 2.0.9 on 2019-02-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190126_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='ncf_regulated_agreements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_agreement_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': '< 0.06 Regulated Agreements',
                'verbose_name': 'Regulated Agreements',
                'ordering': ('ra_agreement_id',),
            },
        ),
        migrations.AlterField(
            model_name='apellio_extensions',
            name='ap_extension_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ncf_collection_agents',
            name='bd_agent_primary_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ncf_collection_agents',
            name='bd_agent_primary_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ncf_collection_agents',
            name='bd_agent_secondary_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ncf_collection_agents',
            name='bd_agent_secondary_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ncf_dd_call_control',
            name='dd_first_bounce_day',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ncf_dd_schedule',
            name='dd_firstbounce_processed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ncf_global_terminations',
            name='written_off',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ncf_settled_agreements',
            name='removed_from_sentinel',
            field=models.BooleanField(default=False),
        ),
    ]
