# Generated by Django 2.0.9 on 2019-05-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190217_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sales_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('other_sales_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prefix', models.CharField(blank=True, max_length=5, null=True)),
                ('customer_number_iteration', models.IntegerField(blank=True, null=True)),
                ('max_tab_create_agreement', models.IntegerField(blank=True, null=True)),
                ('risk_fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dd_days_before_call', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
