# Generated by Django 2.0.9 on 2019-05-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_client_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncf_auddis_addacs_advices',
            name='checked_notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ncf_auddis_addacs_advices',
            name='customercompany',
            field=models.CharField(blank=True, db_column='CustomerCompany', max_length=60, null=True),
        ),
    ]
