# Generated by Django 2.0.9 on 2019-05-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190503_1359'),
    ]

    operations = [

        migrations.AddField(
            model_name='ncf_ddic_advices',
            name='checked_notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ncf_ddic_advices',
            name='customercompany',
            field=models.CharField(blank=True, db_column='CustomerCompany', max_length=60, null=True),
        ),
    ]
