# Generated by Django 2.0.9 on 2019-05-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190503_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ncf_auddis_addacs_advices',
            name='checked_notes',
        ),
        migrations.RemoveField(
            model_name='ncf_auddis_addacs_advices',
            name='customercompany',
        ),
    ]
