# Generated by Django 2.0.9 on 2019-05-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190507_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='holiday_dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='client_configuration',
            name='dd_days_before_drawdown_setup',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client_configuration',
            name='pmt_commission',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='client_configuration',
            name='pmt_yield',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
    ]
