# Generated by Django 2.0.9 on 2019-06-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190509_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='reason_codes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_code', models.CharField(blank=True, max_length=50, null=True)),
                ('reason_text', models.CharField(blank=True, max_length=50, null=True)),
                ('selectable', models.NullBooleanField(default=True)),
            ],
        ),
    ]
