# Generated by Django 2.0.9 on 2019-07-02 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_reason_codes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='apellio_extensions',
            new_name='go_extensions',
        ),
    ]
