# Generated by Django 2.0.9 on 2019-07-02 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190702_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='go_extensions',
            options={'ordering': ('ap_extension_sequence',), 'verbose_name': 'GO App Extension', 'verbose_name_plural': '< 0.00 GO App Extensions'},
        ),
    ]
