# Generated by Django 2.0.9 on 2019-07-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190702_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncf_udd_advices',
            name='dd_in_arrears_app',
            field=models.BooleanField(default=False),
        ),
    ]
