# Generated by Django 2.0.9 on 2019-07-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_ncf_udd_advices_dd_in_arrears_app'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_configuration',
            old_name='risk_fee_amount',
            new_name='bamf_fee_amount_net',
        ),
        migrations.AddField(
            model_name='client_configuration',
            name='bamf_fee_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
