# Generated by Django 2.1.12 on 2019-09-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190719_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncf_settled_agreements',
            name='removed_from_sentinel',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
