# Generated by Django 2.1.12 on 2019-09-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190913_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncf_bacs_files_to_process',
            name='file_identifier',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ncf_bacs_files_to_process',
            name='file_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ncf_bacs_files_to_process',
            name='network_path_archive',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ncf_bacs_files_to_process',
            name='network_path_source',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
