# Generated by Django 2.0.9 on 2019-05-30 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_notes', '0003_auto_20190515_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='agreement_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='customer_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='note_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_notes.Note'),
        ),
    ]
