# Generated by Django 2.0.9 on 2019-05-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_notes', '0004_auto_20190530_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='agreement_doc',
            field=models.NullBooleanField(default=False),
        ),
    ]
