# Generated by Django 2.0.9 on 2019-06-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_notes', '0008_asset_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='archived',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='archived',
            field=models.NullBooleanField(default=False),
        ),
    ]
