# Generated by Django 2.0.9 on 2019-06-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_notes', '0010_asset_follow_up'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='follow_up',
        ),
        migrations.AddField(
            model_name='note',
            name='follow_up',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
