# Generated by Django 2.0.9 on 2019-06-13 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_notes', '0012_auto_20190605_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_priority', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_customer_id', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_agreement_id', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_surname', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_address_line1', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_address_line2', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_address_line3', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_address_line4', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_address_line5', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_mobile_number', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_social_media1', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_social_media2', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_social_media3', models.CharField(blank=True, max_length=50, null=True)),
                ('params', models.TextField(blank=True, max_length=50, null=True)),
                ('archived', models.NullBooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
