# Generated by Django 2.0.9 on 2019-06-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_notes', '0013_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='contact_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
