# Generated by Django 2.0.9 on 2019-06-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_notes', '0015_auto_20190613_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacttype',
            old_name='description',
            new_name='contact_type_description',
        ),
        migrations.RemoveField(
            model_name='contacttype',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='contacttype',
            name='created',
        ),
        migrations.RemoveField(
            model_name='contacttype',
            name='updated',
        ),
        migrations.AddField(
            model_name='contacttype',
            name='contact_type_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
