# Generated by Django 2.0.9 on 2019-07-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_notes', '0021_contacts_contact_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='contact_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
