# Generated by Django 2.0.9 on 2019-05-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection_WorldPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_number', models.CharField(default='', max_length=50)),
                ('agreement_number', models.CharField(default='', max_length=50)),
                ('collection_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('user_name', models.CharField(default='', max_length=50)),
                ('created_on', models.DateTimeField(null=True)),
                ('allocated', models.BooleanField(default=False)),
            ],
        ),
    ]
