# Generated by Django 2.0.9 on 2019-09-11 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_agreement_crud', '0024_auto_20190910_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='datacash_credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_client', models.CharField(blank=True, max_length=50, null=True)),
                ('auth_password', models.CharField(blank=True, max_length=50, null=True)),
                ('bacs_url', models.CharField(blank=True, max_length=150, null=True)),
                ('test_auth_client', models.CharField(blank=True, max_length=50, null=True)),
                ('test_auth_password', models.CharField(blank=True, max_length=50, null=True)),
                ('test_bacs_url', models.CharField(blank=True, max_length=150, null=True)),
                ('funder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core_agreement_crud.go_funder')),
            ],
        ),
    ]
