# Generated by Django 2.0.9 on 2019-05-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_arrears', '0002_arrears_allocation_type_arr_allocation_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrears_allocation_type',
            old_name='arr_allocation_src_type',
            new_name='arr_allocation_src_type_01',
        ),
        migrations.AddField(
            model_name='arrears_allocation_type',
            name='arr_allocation_src_type_02',
            field=models.SmallIntegerField(null=True),
        ),
    ]
