# Generated by Django 2.0.9 on 2019-05-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_arrears', '0003_auto_20190531_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrears_allocation_type',
            name='arr_allocation_src_type_max',
            field=models.SmallIntegerField(null=True),
        ),
    ]
