# Generated by Django 2.0.9 on 2019-08-15 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_arrears', '0004_arrears_allocation_type_arr_allocation_src_type_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrears_summary_arrear_level',
            name='ara_agent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ncf_collection_agents'),
        ),
    ]
