# Generated by Django 2.0.9 on 2019-09-02 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_arrears', '0005_auto_20190815_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrears_summary_arrear_level',
            name='ara_agent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
