# Generated by Django 2.0.9 on 2019-09-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_arrears', '0007_auto_20190905_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrears_summary_arrear_level',
            options={'ordering': ('ara_agreement_id', '-ara_due_date'), 'verbose_name': 'Arrears Summary at Arrear Level', 'verbose_name_plural': 'Arrears Summaries at Arrear Level'},
        ),
        migrations.AlterModelOptions(
            name='receipt_allocations_by_detail',
            options={'ordering': ('rad_agreement_id',), 'verbose_name': 'Receipts Allocations at Detail Level', 'verbose_name_plural': 'Receipts Allocations at Detail Level'},
        ),
    ]
