# Generated by Django 2.1.12 on 2019-09-26 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_arrears', '0008_auto_20190905_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='agent_allocations_control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aac_status', models.CharField(blank=True, max_length=10, null=True)),
                ('aac_agent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Allocation Control',
                'verbose_name_plural': 'Agent Allocation Control',
                'ordering': ('aac_agent_id',),
            },
        ),
    ]
