# Generated by Django 2.0.9 on 2019-05-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_editor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_number', models.CharField(max_length=10)),
                ('editor_given', models.PositiveSmallIntegerField(choices=[(1, 'Yes'), (2, 'No')])),
                ('editor_date', models.DateField(null=True)),
                ('secondary_date', models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
