# Generated by Django 2.0.9 on 2019-06-14 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_agreement_editor', '0002_auto_20190514_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='go_settlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('go_id', models.CharField(max_length=50, null=True, unique=True)),
                ('agreement_id', models.CharField(max_length=10, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('calculated', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('actuals', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('adjustment', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('description', models.CharField(max_length=10, null=True, unique=True)),
                ('reason', models.CharField(max_length=10, null=True, unique=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
