# Generated by Django 2.0.9 on 2019-06-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_editor', '0003_go_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='go_settlement',
            name='sent_to_customer',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='go_settlement',
            name='description',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='go_settlement',
            name='reason',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
