# Generated by Django 2.0.9 on 2019-06-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_editor', '0004_auto_20190614_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='go_settlement',
            name='agreement_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='go_settlement',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='go_settlement',
            name='go_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='go_settlement',
            name='reason',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
