# Generated by Django 2.0.9 on 2019-06-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_editor', '0005_auto_20190614_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='go_settlement',
            name='sent_to_customer',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
