# Generated by Django 2.0.9 on 2019-06-20 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_agreement_editor', '0006_auto_20190614_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='go_editor_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('go_id', models.CharField(max_length=50, null=True)),
                ('agreement_id', models.CharField(max_length=10, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('action', models.CharField(max_length=50, null=True)),
                ('transaction', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
