# Generated by Django 2.0.9 on 2019-06-21 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_editor', '0007_go_editor_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='go_editor_history',
            options={'ordering': ('-updated', 'agreement_id'), 'verbose_name': 'Go Editor History', 'verbose_name_plural': 'Go Editor Historys'},
        ),
    ]
