# Generated by Django 2.0.9 on 2019-06-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_editor', '0008_auto_20190621_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='go_editor_history',
            name='customercompany',
            field=models.CharField(blank=True, db_column='CustomerCompany', max_length=60, null=True),
        ),
    ]
