# Generated by Django 2.0.9 on 2019-09-09 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('core_agreement_crud', '0004_auto_20190903_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='LazyBatchConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=50)),
                ('batch_description', models.TextField(null=True)),
                ('agreement_phase', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], max_length=10, null=True)),
                ('source_type', models.CharField(choices=[('GO', 'GO'), ('SENTINEL', 'SENTINEL')], max_length=10, null=True)),
                ('run_date', models.DateTimeField(blank=True, null=True)),
                ('last_ran', models.DateTimeField(blank=True, null=True)),
                ('repeat', models.SmallIntegerField(default=1)),
                ('priority', models.SmallIntegerField(blank=True, null=True, unique=True)),
                ('in_progress', models.SmallIntegerField(default=0)),
                ('enabled', models.SmallIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('agreement_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core_agreement_crud.go_agreement_definitions')),
            ],
        ),
        migrations.CreateModel(
            name='LazyBatchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('level', models.CharField(choices=[('I', 'Info'), ('W', 'Warning'), ('E', 'Error')], default='I', max_length=1)),
                ('entry', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core_lazybatch.LazyBatchConfig')),
            ],
        ),
    ]
