# Generated by Django 2.0.9 on 2019-09-09 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.TextField()),
                ('task_function', models.CharField(max_length=100)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('last_ran', models.DateTimeField(blank=True, null=True)),
                ('log_file', models.CharField(blank=True, max_length=250, null=True)),
                ('priority', models.SmallIntegerField(blank=True, null=True, unique=True)),
                ('in_progress', models.SmallIntegerField(default=0)),
                ('enabled', models.SmallIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoSchedulerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('task_parameter', models.CharField(max_length=100)),
                ('string', models.TextField(blank=True, null=True)),
                ('decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('integer', models.BigIntegerField(blank=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('go_scheduler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_scheduled_tasks.GoScheduler')),
            ],
        ),
        migrations.CreateModel(
            name='GoSchedulerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('I', 'Info'), ('W', 'Warning'), ('E', 'Error')], default='I', max_length=1)),
                ('entry', models.TextField(blank=True)),
                ('job_ran', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('go_scheduler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_scheduled_tasks.GoScheduler')),
            ],
        ),
    ]
