# Generated by Django 2.0.9 on 2019-05-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_number', models.CharField(max_length=10)),
                ('notice_given', models.PositiveSmallIntegerField(choices=[(1, 'Yes'), (2, 'No')])),
                ('notice_date', models.DateField(null=True)),
                ('secondary_date', models.DateField(null=True)),
            ],
        ),
    ]
