# Generated by Django 2.0.9 on 2019-06-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SageBatchDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('nominal_account_ref', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('department_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('sage_batch_details', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('net_ammount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'core_sage_batch_details',
            },
        ),
        migrations.CreateModel(
            name='SageBatchHeaders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sage_batch_ref', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('sage_batch_type', models.IntegerField(blank=True, null=True)),
                ('total_debit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_credit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('datacash_batch_ref', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'db_table': 'core_sage_batch_headers',
            },
        ),
    ]
