# Generated by Django 2.0.9 on 2019-06-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_sage_export', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SageBatchTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sage_batch_transaction_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('agreementnumber', models.CharField(default='', max_length=10, null=True)),
                ('transactiondate', models.DateTimeField(blank=True, null=True)),
                ('transactionsourceid', models.CharField(max_length=10)),
                ('transactionsourcedesc', models.CharField(blank=True, max_length=20, null=True)),
                ('transtypeid', models.SmallIntegerField(blank=True, null=True)),
                ('transtypedesc', models.CharField(blank=True, max_length=30, null=True)),
                ('transflag', models.CharField(blank=True, max_length=3, null=True)),
                ('transfallendue', models.NullBooleanField()),
                ('transnetpayment', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('transgrosspayment', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('transrunningtotal', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('transcustomercompany', models.CharField(blank=True, max_length=60, null=True)),
                ('transagreementcloseddate', models.DateTimeField(blank=True, null=True)),
                ('transagreementdefname', models.CharField(blank=True, max_length=200, null=True)),
                ('transagreementagreementdate', models.DateTimeField(blank=True, null=True)),
                ('transddpayment', models.NullBooleanField(default=True)),
                ('transagreementauthority', models.CharField(blank=True, max_length=30, null=True)),
                ('transnetpaymentinterest', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('transnetpaymentcapital', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('transactionbatch_id', models.CharField(default='', max_length=15, null=True)),
            ],
            options={
                'db_table': 'core_sage_batch_transactions',
            },
        ),
        migrations.AddField(
            model_name='sagebatchdetails',
            name='sage_batch_detail_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
