# Generated by Django 2.0.9 on 2019-06-25 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_sage_export', '0002_auto_20190625_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sagebatchdetails',
            old_name='net_ammount',
            new_name='net_amount',
        ),
    ]
