# Generated by Django 2.0.9 on 2019-06-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_sage_export', '0004_auto_20190625_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sagebatchtransactions',
            name='sage_batch_typeid',
        ),
    ]
