# Generated by Django 2.0.9 on 2019-06-25 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_sage_export', '0006_auto_20190625_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sagebatchheaders',
            name='datacash_batch_ref',
        ),
    ]
