# Generated by Django 2.0.9 on 2019-06-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_sage_export', '0008_auto_20190625_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='sagebatchheaders',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sagebatchheaders',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
