# Generated by Django 2.0.9 on 2019-06-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_sage_export', '0009_auto_20190625_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sagebatchtransactions',
            name='sage_batch_transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
