# Generated by Django 2.0.9 on 2019-06-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_sage_export', '0010_auto_20190625_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='sagebatchdetails',
            name='account_reference',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
