# Generated by Django 2.0.9 on 2019-06-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_sage_export', '0013_auto_20190626_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sagebatchtransactions',
            name='include',
            field=models.NullBooleanField(default=False),
        ),
    ]
