# Generated by Django 2.0.9 on 2019-06-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_sage_export', '0015_remove_sagebatchtransactions_include'),
    ]

    operations = [
        migrations.AddField(
            model_name='sagebatchtransactions',
            name='include',
            field=models.NullBooleanField(default=True),
        ),
    ]
