# Generated by Django 2.0.9 on 2019-06-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_sage_export', '0016_sagebatchtransactions_include'),
    ]

    operations = [
        migrations.AddField(
            model_name='sagebatchheaders',
            name='processed',
            field=models.DateTimeField(null=True),
        ),
    ]
