# Generated by Django 2.0.9 on 2019-06-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_sage_export', '0017_sagedependencytable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sagedependencytable',
            name='account_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sagedependencytable',
            name='agreement_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sagedependencytable',
            name='nominal_account_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sagedependencytable',
            name='sage_batch_details',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sagedependencytable',
            name='sage_transaction_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sagedependencytable',
            name='tax_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sagedependencytable',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
