# Generated by Django 2.0.9 on 2019-06-26 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_dd_drawdowns', '0008_batchheaders_sagewisdom_processed'),
        ('core_sage_export', '0017_sagebatchheaders_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sagebatchheaders',
            name='batch_header',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core_dd_drawdowns.BatchHeaders', to_field='reference'),
        ),
    ]
