# Generated by Django 2.0.9 on 2019-06-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_sage_export', '0018_sagebatchheaders_batch_header'),
        ('core_sage_export', '0019_sagedependencytable_sage_batch_type'),
    ]

    operations = [
    ]
