# Generated by Django 2.0.9 on 2019-06-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_sage_export', '0020_merge_20190626_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='sagedependencytable',
            name='agreement_phase',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
