# Generated by Django 2.0.9 on 2019-06-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_sage_export', '0021_sagedependencytable_agreement_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sagebatchdetails',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sagebatchdetails',
            name='department_code',
        ),
        migrations.RemoveField(
            model_name='sagebatchdetails',
            name='net_amount',
        ),
        migrations.RemoveField(
            model_name='sagebatchdetails',
            name='sage_batch_detail_id',
        ),
        migrations.RemoveField(
            model_name='sagebatchdetails',
            name='tax_amount',
        ),
        migrations.AddField(
            model_name='sagebatchdetails',
            name='batch_detail_total',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sagebatchdetails',
            name='sage_batch_agreementdefname',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sagebatchdetails',
            name='sage_batch_type',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sagebatchdetails',
            name='sage_batch_typedesc',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sagebatchdetails',
            name='transactionsourcedesc',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sagebatchdetails',
            name='transactionsourceid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='sagebatchdetails',
            table='_GO_Sage_detail_Extract',
        ),
    ]
