# Generated by Django 2.0.9 on 2019-06-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_sage_export', '0022_auto_20190627_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='sagebatchdetails',
            name='sage_batch_ref_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
