# Generated by Django 2.0.9 on 2019-07-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_sage_export', '0023_sagebatchdetails_sage_batch_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sagebatchheaders',
            name='sage_batch_date',
            field=models.DateTimeField(null=True),
        ),
    ]
