# Generated by Django 2.0.9 on 2019-07-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_sage_export', '0025_sagebatchtransactions_remove'),
    ]

    operations = [
        migrations.AddField(
            model_name='sagebatchtransactions',
            name='re_add',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sagebatchtransactions',
            name='remove',
            field=models.NullBooleanField(default=False),
        ),
    ]
