# Generated by Django 2.0.9 on 2019-07-02 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_sage_export', '0026_auto_20190702_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sagebatchtransactions',
            name='re_add',
        ),
    ]
