# Generated by Django 2.0.9 on 2019-07-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_sage_export', '0027_remove_sagebatchtransactions_re_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='sagebatchheaders',
            name='save_the_click',
            field=models.NullBooleanField(default=True),
        ),
    ]
