# Generated by Django 2.0.9 on 2019-07-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_sage_export', '0028_sagebatchheaders_save_the_click'),
    ]

    operations = [
        migrations.AddField(
            model_name='sagebatchheaders',
            name='processing',
            field=models.NullBooleanField(default=False),
        ),
    ]
