# Generated by Django 2.0.9 on 2019-07-04 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_sage_export', '0029_sagebatchheaders_processing'),
    ]

    operations = [
        migrations.CreateModel(
            name='SageBatchLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=36, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('released', models.DateTimeField(null=True)),
                ('sage_batch_header', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core_sage_export.SageBatchHeaders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
