# Generated by Django 2.0.9 on 2019-05-10 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='go_agreement_querydetail',
            options={'ordering': ('-agreementagreementdate', '-agreementnumber'), 'verbose_name': 'Agreement Query Detail', 'verbose_name_plural': 'Agreement Query Details'},
        ),
    ]
