# Generated by Django 2.0.9 on 2019-05-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_crud', '0002_auto_20190510_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='go_agreement_index',
            name='agreement_closed_reason',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
