# Generated by Django 2.0.9 on 2019-05-23 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_crud', '0003_go_agreement_index_agreement_closed_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='go_agreement_querydetail',
            options={'ordering': ('agreement_stage', '-agreementagreementdate', '-agreementnumber'), 'verbose_name': 'Agreement Query Detail', 'verbose_name_plural': 'Agreement Query Details'},
        ),
    ]
