# Generated by Django 2.0.9 on 2019-05-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_crud', '0006_auto_20190523_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='go_agreement_index',
            name='consolidation_info',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
