# Generated by Django 2.0.9 on 2019-07-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_crud', '0009_auto_20190605_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='go_agreement_index',
            name='bamf_flag',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='go_agreement_index',
            name='risk_flag',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='go_agreement_index',
            name='secondary_flag',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='go_agreement_index',
            name='security_flag',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='go_agreement_index',
            name='title_flag',
            field=models.NullBooleanField(),
        ),
    ]
