# Generated by Django 2.0.9 on 2019-07-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_crud', '0010_auto_20190703_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='go_agreement_index',
            name='bamf_flag',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='go_agreement_index',
            name='risk_flag',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='go_agreement_index',
            name='secondary_flag',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='go_agreement_index',
            name='security_flag',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='go_agreement_index',
            name='title_flag',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
