# Generated by Django 2.0.9 on 2019-07-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_crud', '0011_auto_20190704_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='go_agreement_index',
            name='closed_info',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
