# Generated by Django 2.0.9 on 2019-07-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_crud', '0012_go_agreement_index_closed_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='go_agreement_index',
            name='closed_info',
        ),
        migrations.AddField(
            model_name='go_agreement_querydetail',
            name='agreement_closed_reason',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
