# Generated by Django 2.0.9 on 2019-07-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_crud', '0013_auto_20190708_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='go_account_transaction_summary',
            name='transactionstatus',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
