# Generated by Django 2.0.9 on 2019-07-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_crud', '0014_go_account_transaction_summary_transactionstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='go_agreement_index',
            name='amf_flag',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
