# Generated by Django 2.0.9 on 2019-07-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_crud', '0015_go_agreement_index_amf_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='go_agreement_index',
            name='manual_payments',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
