# Generated by Django 2.0.9 on 2019-08-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_crud', '0018_auto_20190718_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='go_account_transaction_detail',
            name='transgrosspayment',
            field=models.DecimalField(blank=True, db_column='TransGrossPayment', decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='go_account_transaction_detail',
            name='transpayproid',
            field=models.IntegerField(blank=True, db_column='TransPayProID', null=True),
        ),
        migrations.AddField(
            model_name='go_account_transaction_detail',
            name='transpayprointerest',
            field=models.DecimalField(blank=True, db_column='TransPayProInterest', decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='go_account_transaction_detail',
            name='transpayproprincipal',
            field=models.DecimalField(blank=True, db_column='TransPayProPrincipal', decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='go_account_transaction_detail',
            name='transvatpayment',
            field=models.DecimalField(blank=True, db_column='TransVatPayment', decimal_places=4, max_digits=19, null=True),
        ),
    ]
