# Generated by Django 2.0.9 on 2019-07-24 12:16

from django.db import migrations

from core.models import ncf_applicationwide_text


def populate_ncf_applicationwide_text(apps, schema_editor):

    try:
        new_rec = ncf_applicationwide_text(app_text_code='905', app_text_set='1', app_text_description='AWAITING REVIEW')
        new_rec.save()
    except:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_crud', '0018_auto_20190718_1426'),
    ]

    operations = [
        migrations.RunPython(populate_ncf_applicationwide_text)
    ]
