# Generated by Django 2.0.9 on 2019-08-06 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_crud', '0019_auto_20190724_1216'),
        ('core_agreement_crud', '0019_auto_20190805_1132'),
    ]

    operations = [
    ]
