# Generated by Django 2.0.9 on 2019-08-07 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_crud', '0020_merge_20190806_0927'),
        ('core_agreement_crud', '0020_merge_20190807_1220'),
    ]

    operations = [
    ]
