# Generated by Django 2.0.9 on 2019-08-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_crud', '0021_merge_20190807_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='transition_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreementnumber', models.CharField(db_column='AgreementNumber', default='', max_length=10, null=True)),
                ('transition_date', models.DateTimeField(auto_now_add=True)),
                ('from_system', models.CharField(blank=True, max_length=50, null=True)),
                ('to_system', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
