# Generated by Django 2.0.9 on 2019-08-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_crud', '0022_transition_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='go_agreement_index',
            name='agreement_status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
