# Generated by Django 2.0.9 on 2019-09-10 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_crud', '0023_go_agreement_index_agreement_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='go_funder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funder_code', models.SmallIntegerField(blank=True, null=True)),
                ('funder_description', models.CharField(blank=True, max_length=50, null=True)),
                ('funder_SUN', models.CharField(blank=True, max_length=50, null=True)),
                ('selectable', models.NullBooleanField()),
                ('batch_prefix', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='go_account_transaction_summary',
            name='transactionbatch_id',
            field=models.CharField(db_column='TransactionBatch_id', default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='go_agreement_index',
            name='funder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core_agreement_crud.go_funder'),
        ),
    ]
