# Generated by Django 2.1.12 on 2019-09-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_crud', '0025_go_funder_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='go_agreement_index',
            name='companies_house_status_flag',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
