# Generated by Django 2.0.9 on 2019-05-01 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DDHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_no', models.CharField(db_column='agreement_id', max_length=10)),
                ('sequence', models.IntegerField(db_column='sequence')),
                ('reference', models.CharField(blank=True, db_column='reference', max_length=20, null=True)),
                ('dd_reference', models.CharField(blank=True, db_column='dd_reference', max_length=50, null=True)),
                ('account_name', models.CharField(db_column='account_name', max_length=60)),
                ('account_number', models.CharField(db_column='account_number', max_length=8)),
                ('sort_code', models.CharField(db_column='sort_code', max_length=6)),
                ('effective_date', models.DateField(db_column='effective_date', null=True)),
                ('cancelled_date', models.DateTimeField(db_column='cancelled_date', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_direct_debits_history',
            },
        ),
        migrations.CreateModel(
            name='DDLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_no', models.CharField(db_column='agreement_id', max_length=10)),
                ('reference', models.CharField(blank=True, db_column='reference', max_length=20, null=True)),
                ('dd_reference', models.CharField(blank=True, db_column='dd_reference', max_length=50, null=True)),
                ('account_name', models.CharField(db_column='account_name', max_length=60)),
                ('account_number', models.CharField(db_column='account_number', max_length=8)),
                ('sort_code', models.CharField(db_column='sort_code', max_length=6)),
                ('method', models.CharField(choices=[('setup', 'setup'), ('revoke', 'revoke')], db_column='method', max_length=10)),
                ('success', models.BooleanField(db_column='success')),
                ('info', models.TextField(db_column='info')),
                ('request', models.TextField(blank=True, db_column='request', null=True)),
                ('response', models.TextField(blank=True, db_column='response', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_direct_debits_log',
            },
        ),
    ]
