# Generated by Django 2.0.9 on 2019-07-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_direct_debits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddhistory',
            name='valid',
            field=models.NullBooleanField(db_column='dd_valid', default=False),
        ),
    ]
