# Generated by Django 2.1.12 on 2019-09-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_direct_debits', '0002_ddhistory_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddhistory',
            name='provider',
            field=models.CharField(blank=True, choices=[('datacash', 'datacash'), ('eazycollect', 'eazycollect')], max_length=100, null=True),
        ),
    ]
