# Generated by Django 2.1.12 on 2019-09-13 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_agreement_crud', '0024_auto_20190910_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
                ('client_code', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('funder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core_agreement_crud.go_funder')),
            ],
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_id', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
                ('headers', models.TextField(blank=True, null=True)),
                ('request', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
