# Generated by Django 2.1.12 on 2019-09-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_eazycollect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RequestTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_object', models.TextField(blank=True, null=True)),
                ('kwargs', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='requestlog',
            name='http_method',
            field=models.CharField(blank=True, choices=[('GET', 'GET'), ('PUT', 'PUT'), ('POST', 'POST'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='request_type',
            field=models.CharField(blank=True, choices=[('payment', 'payment'), ('customer', 'customer'), ('contract', 'contact')], max_length=50, null=True),
        ),
    ]
