# Generated by Django 2.1.12 on 2019-09-13 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_eazycollect', '0002_auto_20190913_1719'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestLog',
        ),
    ]
