# Generated by Django 2.1.12 on 2019-09-13 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_eazycollect', '0004_requestlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerId',
        ),
    ]
