# Generated by Django 2.1.12 on 2019-09-16 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_crud', '0024_auto_20190910_1624'),
        ('core_eazycollect', '0005_delete_customerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ez_customer_id', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core_agreement_crud.go_customers')),
            ],
        ),
    ]
