# Generated by Django 2.1.12 on 2019-09-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_eazycollect', '0008_auto_20190916_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='request_type',
            field=models.CharField(blank=True, choices=[('payment', 'payment'), ('customer', 'customer'), ('contract', 'contract')], max_length=50, null=True),
        ),
    ]
