# Generated by Django 2.1.12 on 2019-09-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_eazycollect', '0009_auto_20190916_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerid',
            name='agreement_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
