# Generated by Django 2.1.12 on 2019-09-16 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_eazycollect', '0010_customerid_agreement_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerid',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerid',
            name='customer_ref',
        ),
    ]
