# Generated by Django 2.1.12 on 2019-09-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_eazycollect', '0011_auto_20190916_1459'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerId',
            new_name='Contracts',
        ),
    ]
