# Generated by Django 2.1.12 on 2019-09-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_eazycollect', '0012_auto_20190916_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='ez_contract_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='ez_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
