# Generated by Django 2.1.12 on 2019-09-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_eazycollect', '0016_auto_20190918_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbacklog',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callbacklog',
            name='processed',
            field=models.NullBooleanField(),
        ),
    ]
