# Generated by Django 2.1.12 on 2019-09-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_eazycollect', '0018_auto_20190918_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlog',
            name='agreement_id',
        ),
        migrations.AddField(
            model_name='requestlog',
            name='source_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='source_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
