# Generated by Django 2.1.12 on 2019-09-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_eazycollect', '0019_auto_20190918_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='source_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
